// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqynfpfkqibeasjzpgye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxeW5mcGZrcWliZWFzanpwZ3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNjc3NzksImV4cCI6MjA1MDg0Mzc3OX0.5wdQFBs8SrTY73rgretcYDTTKddt362deCA90juyC6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);